### ISSUE TITLE
Style order issue when using unocss in nuxt-swiper

### ISSUE THREAD

**Issue by lxccc812** [cpreston321/nuxt-swiper#104]
application:
```vue
<Swiper
    :modules="[]"
    :slides-per-view="'auto'"
    :grab-cursor="true"
    :free-mode="true"
    class="w-[calc(100%-20px)] overflow-hidden rd-2.5 py-2.5"
>
    <SwiperSlide v-for="item in screenshots" :key="item.id" class="mr-2 w-a last:mr-0">
        <img
            :src="item.imgSrc"
            class="h-62.5 w-a rd-2.5 bg-[#00000066]"
        />
    </SwiperSlide>
</Swiper>
```

local:
![QIKD`6%YOPK%`CLN VPLQFS](https://github.com/cpreston321/nuxt-swiper/assets/110974969/328c23c1-75ec-45c3-96cc-0d38ef0ba2a2)
![HCNX`ON2`KYO6~%4@`N QS1](https://github.com/cpreston321/nuxt-swiper/assets/110974969/fe1cd35b-fdd5-44a8-a2c7-730060cd83cb)

after build:
![RWL9~Z96{2I3IO87OKA3X_N](https://github.com/cpreston321/nuxt-swiper/assets/110974969/91b522bc-52cf-4de6-94db-f84837b8d7bc)
![CNV}JHH2~8}Q`MLJCBCXNIB](https://github.com/cpreston321/nuxt-swiper/assets/110974969/7fb8095a-8b32-46aa-8be1-7d5f1bc80240)
As a result, the style cannot be displayed as expected.

nuxt-swiper 1.2.2
@unocss/nuxt 0.57.1

Solution Add `!important`

**Comment by cpreston321** [comment]
I would use the `@apply` directive within unocss. This way you can target the swiper-class within the css that can overwrite the default styles. https://unocss.dev/transformers/directives#usage or you can use the unocss important modifier `!py.-2.5`

**Comment by lxccc812** [comment]
yeah , `!` is right
![image](https://github.com/cpreston321/nuxt-swiper/assets/110974969/8544fcb6-d634-476d-8d95-f21c325e99a6)

**Comment by The73756** [comment]
Same issue. Using !important is not a good solution!
