### ISSUE TITLE
Not compatible with latest version of nuxt 3.8.0

### ISSUE THREAD

**Issue by vhovorun** [cpreston321/nuxt-swiper#105]
Reproduction link
https://stackblitz.com/edit/github-5d7cdq?file=app.vue,components%2FSwiperControls.vue
It gives an issue when you to try to use Navigation or Pagination modules
![image](https://github.com/cpreston321/nuxt-swiper/assets/129970958/2d3e9520-af35-4672-9ac2-869564b8cbd7)

**Comment by pronkost** [comment]
You should use SwiperPagination and SwiperPagination.
