### ISSUE TITLE
Problem with destroing Swiper

### ISSUE THREAD

**Issue by lefhl** [cpreston321/nuxt-swiper#107]
The situation: I have a block where data is rendered as a usual grid for desktop and as a slider for mobile phones. I observe the page size for determination whether I have mobile or desktop screen. If this is a desktop, then I just try to destroy the slider. In code it looks like^
```vue
<swiper
      class="why-we"
      :slides-per-view="1"
      @swiper="(swiper) => swiperInstance = swiper"
>...</swiper>
``` 
```ts
watch(() => swiperInstance.value, () => {
  if (!isMobileScreen.value) {
    swiperInstance.value?.destroy()
  }
})
```

But I have this mistake: TypeError: "Cannot read properties of undefined (reading 'loop')"

![image](https://github.com/cpreston321/nuxt-swiper/assets/56530714/a7089a9d-88ea-4e4e-beba-9aabcad2f7d9)
![image](https://github.com/cpreston321/nuxt-swiper/assets/56530714/87aad543-3e39-48a7-8eda-537720487c5e)

How can I fix it and reach expected behaviour?

**Comment by JoGlows** [comment]
maybe swiperInstance.value?.destroy(false, false)

**Comment by lefhl** [comment]
@JoGlows made destroy(false, true) and this way it works. Thanx!
