### ISSUE TITLE
Module "SwiperFreeMode" doesn't work

### ISSUE THREAD

**Issue by hellencheetah** [cpreston321/nuxt-swiper#110]
Environment:
nuxt: 3.8.2
nuxt-swiper: 1.2.2

I can't find any info how to make it work. 
Every feedback item has fixed width.

```
  <Swiper
      :modules="[SwiperFreeMode]"
     :slides-per-view="'auto'"     
  >
    <SwiperSlide
        v-for="item in feedbacks"
        :key="item.id"
    >
      <div>{{feedback}}</div>
    </SwiperSlide>
  </Swiper>
```

**Comment by cpreston321** [comment]
Please check this example from Swiper js: https://codesandbox.io/p/sandbox/xfw4zx?file=/src/App.vue
