### ISSUE TITLE
how can i set swiper1's control to swiper2

### ISSUE THREAD

**Issue by wangjialuo** [cpreston321/nuxt-swiper#121]
<Swiper :modules="[SwiperAutoplay, SwiperController]"
                  :loop="false"
                  slidesPerView="auto"
                  :freeMode="true"
                  :slideToClickedSlide="true"
                  ref="swiper1"
                  id="swiper1"
                  @after-init="onAfterInit"
                  :on="{
                      init: init1  
                  }"
                  :autoplay="{
                        delay: 2000,
                        disableOnInteraction: true,
                  }">
                  <SwiperSlide v-for="(item,index) in list" :key="index">
                        <div class="slide" flex>
                                    <div class="left" w-35px flex-shrink-0 col-start-center>
                                          <img src="@/assets/img/dian.png" alt="" w-28px >
                                    </div>
                                    <div class="right" flex flex-col>
                                          <div pb-20px pl-15px text="48px" class="year">{{ item.year }}</div>
                                          <img src="" alt="" w-515px h-300px>
                                          <p pt-20px>{{ item.describe }}</p>
                                    </div> 
                              </div>
                  </SwiperSlide>
                  
            </Swiper>        
            <div class="year" w-1548px mx-auto  pt-73px >
                  <div class="mark" t-73px h-64px></div>
                  <Swiper
                  ref="swiper2"
                  id="swiper2"
                  mx-auto
                  :modules="[SwiperAutoplay, SwiperController]"
                  :loop="false"
                  slidesPerView="auto"
                  :freeMode="true"
                  :slideToClickedSlide="true"
                  :centeredSlides=true
                  :autoplay="{
                        delay: 2000,
                        disableOnInteraction: true,
                  }">
                  <SwiperSlide v-for="(item,index) in list" :key="index">
                        <div pb-20px pl-100px text="36px stroke-sm" class="year">{{ item.year }}</div>
                  </SwiperSlide>
            </Swiper>

**Comment by Andykrvua** [comment]
<script setup>
const mainSwiper = ref(null);
const thumbsSwiper = ref(null);

const setThumbsSwiper = (swiper) => {
  thumbsSwiper.value = swiper;
};

const setMainSwiper = (swiper) => {
  mainSwiper.value = swiper;
};

onMounted(() => {
  // fix slider initialization after change route (if page transition = 300ms)
  if (mainSwiper.value) {
    setTimeout(() => {
      mainSwiper.value.update();
    }, 400);
  }
});
</script>

<template>
    <Swiper
      @swiper="setMainSwiper"
      :modules="[SwiperThumbs]"
      :thumbs="{ swiper: thumbsSwiper }"
    >
    ...
        <Swiper
      @swiper="setThumbsSwiper"
      :modules="[SwiperThumbs]"
    >
