### ISSUE TITLE
releaseOnEdges not working

### ISSUE THREAD

**Issue by chinoKwi** [cpreston321/nuxt-swiper#131]
releaseOnEdges in Mousewheel Control does not work properly
[https://stackblitz.com/edit/github-j52b7g?file=app.vue](https://stackblitz.com/edit/github-j52b7g?file=app.vue)

Swiper Docs: [https://swiperjs.com/swiper-api#param-releaseOnEdges](https://swiperjs.com/swiper-api#param-releaseOnEdges)

**Comment by dw5** [comment]
It's best to avoid this package, heck it's own demo is not working now, and for me after npm update of packages it broke carousel which used this. Just port to https://swiperjs.com/element
![image](https://github.com/user-attachments/assets/2664f6ff-e96e-43ee-bd31-971824a1a8a5)

**Comment by chinoKwi** [comment]
OK, Thank you for your suggestion!
