### ISSUE TITLE
How to use paginations?

### ISSUE THREAD

**Issue by bobur-ops** [cpreston321/nuxt-swiper#28]
![image](https://user-images.githubusercontent.com/79460836/213189308-579bcbe0-27a4-4480-b8c6-3abc113f9adb.png)
![image](https://user-images.githubusercontent.com/79460836/213189386-027df332-7b03-45f4-bee4-ff184e8abfb5.png)

Guys I don't understand why the pagination is not showing. Can you tell me what am I doing wrong?

**Comment by cpreston321** [comment]
Can you make simple reproduction in stackblitz ? I can try to debug it

**Comment by bobur-ops** [comment]
I don't know how but it is working now
