### ISSUE TITLE
How to use attributes such as breakpoints and spacebetween ?

### ISSUE THREAD

**Issue by omeersari** [cpreston321/nuxt-swiper#30]
Hello in my nuxt 2 project I used swiper with swiper options in data such as:

```js
swiperOption: {
          slidesPerView: 3,
          spaceBetween: 30,
          pagination: {
            el: '.swiper-pagination',
            clickable: true
          },
          breakpoints: {
            1024: {
              slidesPerView: 3,
              spaceBetween: 10
            },
            768: {
              slidesPerView: 2,
              spaceBetween: 10
            },
            640: {
              slidesPerView: 1,
              spaceBetween: 10
            },
            320: {
              slidesPerView: 1,
              spaceBetween: 10
            }
          }
      }
```

Now I want my project to be Nuxt 3 and I use this module to make swiper work. However the things that I used before such as breakpoints and spacebetween, I can't use them anymore. Am I missing something or is there a way to use them in Nuxt 3 too ? 

Like this isnt working:

```js
<Swiper
      :modules="[SwiperAutoplay, SwiperEffectCreative, SwiperPagination, SwiperThumbs]"
      :slides-per-view="2"
      :loop="true"
      :space-between="20"
      :pagination="{
        clickable: true,
      }"
      :effect="'creative'"
      :autoplay="{
        delay: 2000,
        disableOnInteraction: true,
      }"
      :creative-effect="{
        prev: {
          shadow: false,
          translate: ['-20%', 0, -1],
        },
        next: {
          translate: ['100%', 0, 0],
        },
      }"
... rest of the code
/>



```

**Comment by cpreston321** [comment]
@omeersari  Can you provide a simple stackblitz reproduction? I'll take a look for you.

**Comment by omeersari** [comment]
@cpreston321 https://stackblitz.com/edit/nuxt-starter-5l17f5?file=app.vue

here, space between works actually but couldn't breakpoints work

**Comment by cpreston321** [comment]
@omeersari https://stackblitz.com/edit/nuxt-starter-9vuchk?file=app.vue

Couple things creative effect will have to be adjusted as it affected breakpoints and here is a somewhat working verison.
