### ISSUE TITLE
Nuxt 3.1.0 Hydration children mismatch

### ISSUE THREAD

**Issue by ccharmai** [cpreston321/nuxt-swiper#31]
Hello, I found a bug when working with an updated version of nuxt

`[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom.`
`Hydration completed but contains mismatches.`

[Minimal reproduction](https://stackblitz.com/edit/nuxt-starter-f8qx7r?file=app.vue). The error can be seen in the console

**Comment by cpreston321** [comment]
@ccharmai This is upstream for `nuxt` issue will be patched.

**Comment by cpreston321** [comment]
@ccharmai should be fixed in nuxt 3.1.1! Let me know if this is resolved if so, I will close ticket.

Thanks 🙏🏻

**Comment by ccharmai** [comment]
@cpreston321 hello! problem fixed in Nuxt 3.1.1
