### ISSUE TITLE
Change slide programmatically?

### ISSUE THREAD

**Issue by notflip** [cpreston321/nuxt-swiper#32]
I have a layout where the default pagination is not going to work for me, I would like to move it to another place in the DOM. Is it possible to use an event to go to the next and prev slide?

**Comment by cpreston321** [comment]
Please reference this thread and playground to have better control over slides! https://github.com/cpreston321/nuxt-swiper/issues/8#issuecomment-1279422385

Let me know if you have any other questions thanks 🙏🏻

**Comment by notflip** [comment]
@cpreston321 Perfect! Thanks
