### ISSUE TITLE
SwiperLazy module returns en error

### ISSUE THREAD

**Issue by luigigorlero** [cpreston321/nuxt-swiper#40]
Hello! Since the update from 0.1.9, any Swiper components that use the module [SwiperLazy] return an error, did it become a default functionality?

**Comment by cpreston321** [comment]
Hey @luigigorlero it seems they taken out the module in favor of letting the browser handle Lazy Loading. You can read more on it here: https://swiperjs.com/swiper-api#lazy-loading

**Comment by cpreston321** [comment]
Alternative would be to `loading="lazy"` as an attr on the image itself.

**Comment by cpreston321** [comment]
@luigigorlero I updated README to let other users know they taken it out. Since nuxt-swiper `v1.0.0` is a major change you can fallback to `0.1.9` in the meantime if you like using that module.

I will close this issue for now. Thanks for the letting me know! 💚
