### ISSUE TITLE
Custom navigation buttons

### ISSUE THREAD

**Issue by ideafm** [cpreston321/nuxt-swiper#44]
Any way to use custom navigation buttons, using $refs?

**Comment by ideafm** [comment]
it's not working this way
` <Swiper :slides-per-view="1" :loop="true" :modules="[SwiperNavigation]" :navigation="{prevEl: $refs.prev, nextEl: $refs.next}">`

**Comment by cpreston321** [comment]
@ideafm Hello 👋 

Have you tried using the `SwiperController` module ? https://swiperjs.com/vue#controller ?

**Comment by cpreston321** [comment]
Also per use case as noted in docs since `SwiperNavigation` is part of core modules it had no correlation to refs only to classnames as noted here: 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/6619884/222471353-5a9632ff-e2ac-4552-aff5-203dd9fa9975.png">

**Comment by ideafm** [comment]
It could be an HTMLElement
<img width="1072" alt="Снимок экрана 2023-03-02 в 18 25 50" src="https://user-images.githubusercontent.com/6522186/222472264-df08ace8-a537-4641-bb6e-f69807cca230.png">

So, it have no way to using refs?
But in case when I have 3 Components (e.g. <ProductSlider />) I can't using class names, cause it will be work only on first instance

**Comment by cpreston321** [comment]
https://swiperjs.com/vue#use-swiper

**Comment by amishiro** [comment]
うへ。vue3-calusel、動かせたけど、カスタマイズしようとすると、余分な記述がどんどん増えそう。
他のも検討する。

**Comment by Kristoffer95** [comment]
Worked for me:

```vue
<Swiper
  :modules="[SwiperNavigation]"
  :slides-per-view="1"
  :navigation="{
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  }">
  <SwiperSlide v-for="(val, index) in 10" :key="index">
    <h4>{{ val }}</h4>
  </SwiperSlide>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</Swiper>
```

**Comment by cpreston321** [comment]
Close for being stale, there are some closed issues that solves for this as we can reference these.
