### ISSUE TITLE
useSwiper() not working....

### ISSUE THREAD

**Issue by sohilpro** [cpreston321/nuxt-swiper#50]
` useSwiper()` 
### [Vue warn]: injection "swiper" not found.

**Comment by cpreston321** [comment]
Can you link your project so I can re produce ? Thanks!

**Comment by sohilpro** [comment]
> Can you link your project so I can re produce ? Thanks!


I use localhost, I just started the project.  And I wanted to customize the navigation button. But it seems to have a problem. Please check

**Comment by cpreston321** [comment]
Is your project on Github ? or can you reproduce it on stackblitz? 

I need to know what the code looks like in order to debug the problem!

Thanks,
CP

**Comment by cpreston321** [comment]
You can copy your code over to this -> https://stackblitz.com/github/cpreston321/nuxt-swiper/tree/main/examples/swiper-basic?file=app.vue 

Then share the link with me.

**Comment by cpreston321** [comment]
You can copy your code over to this -> https://stackblitz.com/github/cpreston321/nuxt-swiper/tree/main/examples/swiper-basic?file=app.vue 

Then share the link with me.

**Comment by glennovische** [comment]
I have the same problem. 
const swiper = useSwiper();
 <button @click="swiper.slideNext()">Next</button>

**Comment by moyukingS** [comment]
> You can copy your code over to this -> https://stackblitz.com/github/cpreston321/nuxt-swiper/tree/main/examples/swiper-basic?file=app.vue
> 
> Then share the link with me.

[https://stackblitz.com/edit/github-lx7hky?file=app.vue ](url)

**Comment by haexhub** [comment]
Is there any update on this?
I did exactly the same as you suggested [here](https://stackblitz.com/edit/nuxt-starter-4snpbh?file=components/Slides.vue), but with the newest version and it's not working.
