### ISSUE TITLE
bug: images not centered when used with loop

### ISSUE THREAD

**Issue by Sandros94** [cpreston321/nuxt-swiper#51]
While using `:slidesPerView="'auto'"` and `:centered-slides="true"`, if I try to enable the loop `:loop="true"` the images get messed up are no longer centered all the times.

If I remove `:loop="true"` all the images are centered correctly, but I lose the loop.

Here is a [stackblitz reproduction](https://stackblitz.com/edit/nuxt-starter-jfogjs?file=components/content/slide-show.vue).

First and last images mostly not centered:
![image](https://user-images.githubusercontent.com/13056429/229386431-f3150328-5497-4900-aec5-3a3aeef47f50.png)

Other images centered while scrolling:
![image](https://user-images.githubusercontent.com/13056429/229386482-2f43cad4-995c-4dbe-9e8e-741130f0b45b.png)

P.S.: I've noticed that after the first load on stackblitz the first image could look centered, but event a simple reload brakes it.

**Comment by Sandros94** [comment]
@cpreston321 do you have any link for the upstream bug documentation?

**Comment by cpreston321** [comment]
@Sandros94 The only reason I said it was upstream was because the `nuxt-swiper` package makes it quickly available to auto-imports and it includes the package. I don't really do anything outside that. This seems that it pertains to the core package `swiper` which I have no control over :/

**Comment by cpreston321** [comment]
`nuxt-swiper` is based off `swiper/vue` which includes `swiper/core`. Swiper elements is somewhat new in the v9 but it only make since it's vue I use the vue package. 

Thanks,
CP

**Comment by Sandros94** [comment]
Sorry to ask this here, but I wouldn't like to create a new issue just for such small question.

To my understanding most of the modules within nuxt-swiper are automatically imported, without the need to add for example: `:modules="[SwiperAutoplay, SwiperMousewheel, SwiperPagination]"`.
But why do I still have to in the reproduction example?

If I don't have modules specified nor in the nuxt.config.ts nor in the component I cannot use modules like Pagination, Mousewheel or similars.

**Comment by cpreston321** [comment]
@Sandros94

I will have to look into this.. based on the docs you have to import each module. The settings types might be available without the modules imported but it will not work like how it was intended but sadly the `swiper` requires you to pass the module in order to use these specific `modules`. Unless they change the API how to make modules work so it has to work like this. The packages prefixes `Swiper{ModuleName}` because of common namespace collisions potentially but the prefix can be modified in the config.

**Comment by Sandros94** [comment]
Ok, yes this was one of the reasons why I tried swiper element, but then I lose other functionalities.
