### ISSUE TITLE
Is there exported `SwiperOptions` for type declarations ?

### ISSUE THREAD

**Issue by nasirDoe** [cpreston321/nuxt-swiper#54]
like this:

`import type { SwiperOptions } from 'swiper'`

**Comment by cpreston321** [comment]
you can export the types from the `swiper/vue` package. It should include the types if you want to manually import them.

**Comment by cpreston321** [comment]
You can also check out the export within the main `package.json` here: https://www.npmjs.com/package/swiper?activeTab=code

Thanks,
CP
