### ISSUE TITLE
I have a problem about SwiperNavigation

### ISSUE THREAD

**Issue by Chaoc2624** [cpreston321/nuxt-swiper#56]
When I use nuxt-swiper in Nuxt, and click on a NuxtLink to a page, if the page has use nuxt-swiper, the click events for the nextEl and prevEl of the swiper in that page will not work.
My nuxt version is 3.3.1,nuxt-swiper version is 1.0.1

When I click the button in <NextBtn/>, the Chrome console output -----> Uncaught TypeError: Cannot read properties of undefined (reading 'slideNext')  like this  
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/87065778/231366098-8d22dc5f-69c5-4b35-8b54-c93591dacf43.png">

And this is my code 
![image](https://user-images.githubusercontent.com/87065778/231366193-deeb72f4-46fb-4cd7-afd9-12f9553f087f.png)

![image](https://user-images.githubusercontent.com/87065778/231366282-3f2e5183-7de9-489e-ae19-5e25005a2d24.png)

**Comment by cpreston321** [comment]
has to within the `<Swiper><NextBtn /></Swiper>`

**Comment by Chaoc2624** [comment]
oh, i see, but i also want to ues this function when i chick the swiper  navigation  **.swiper-button-nex** and **.swiper-button-prev**

then i bind @click on the _**wiper.slideNext()**_  , 
the chrome console output **Cannot read properties of undefined (reading 'slideNext')**


initial, I wanted to know was how I make the nuxt-swiper‘s SwiperSlide nxet or prev when I click nuxt-link to one page and click  the swiper  navigation  **.swiper-button-nex** and **.swiper-button-prev** , and I find the nuxt-swiper also not autoplay too, i think i cant direct ues **.swiper-button-nex** and **.swiper-button-prev** alse so  troublesome

**Comment by Chaoc2624** [comment]
oh, i see, but i also want to ues this function when i chick the swiper  navigation  **.swiper-button-nex** and **.swiper-button-prev**

then i bind @click on the _**wiper.slideNext()**_  , 
the chrome console output **Cannot read properties of undefined (reading 'slideNext')**


initial, I wanted to know was how I make the nuxt-swiper‘s SwiperSlide nxet or prev when I click nuxt-link to one page and click  the swiper  navigation  **.swiper-button-nex** and **.swiper-button-prev** , and I find the nuxt-swiper also not autoplay too, i think i cant direct ues **.swiper-button-nex** and **.swiper-button-prev** alse so  troublesome
