### ISSUE TITLE
How to implement custom navigation?

### ISSUE THREAD

**Issue by thezumrad** [cpreston321/nuxt-swiper#57]
pagination: {
          clickable: true,
          renderBullet: function (index, className) {
            return '<span class="' + className + '">' + (index + 1) + '</span>';
          },
        },

**Comment by FranciscoKloganB** [comment]
I think the community needs a bit more context to be able to help you @thezumrad.

The best I can do for you at this moment is sharing my code snippets.

```ts
const paginationConfig: SwiperOptions['pagination'] = {
  el: '.swiper-pagination',
  enabled: false,
  renderFraction: (c, t) => renderFraction(c, t),
  type: 'fraction',
}

function renderFraction(currentClass: string, totalClass: string) {
  return `
    <div class="mx-auto bg-slate-900/60 dark:bg-white/60 text-white dark:text-gray-800 rounded-lg max-w-fit px-2 py-1">
      <span class="capitalize">${t('others.photo')}</span>
      <span class="${currentClass}"></span>
      <span>${t('connectors.of')}</span>
      <span class="${totalClass}"></span>
    </div>
  `
}

<template>
  <Swiper :pagination="paginationConfig" />
</template>
```

**Comment by thezumrad** [comment]
Hey @FranciscoKloganB! Thanks for your reply.
I need to have custom pagination with dynamic images as thumbnails coming from an array that I will pull from cms.

I use nuxt3  

Here is my code:

`
<template>
  <section>
    <div class="py-24">
      <div class="container">
        <Swiper  :modules="[SwiperAutoplay, SwiperEffectCreative, SwiperPagination]" :slides-per-view="1" :loop="true"  
        :pagination="{clickable: true}">
          <SwiperSlide v-for="slide in 10" :key="slide">
            <strong>{{ slide }}</strong>
          </SwiperSlide>
            <SwiperPagination />
        </Swiper>
      </div>
    </div>
  </section>
</template>`

**Comment by thezumrad** [comment]
@FranciscoKloganB Thanks for your reply. I solved it with Swiper Thumbs
