### ISSUE TITLE
tree shaking does not seem to work

### ISSUE THREAD

**Issue by jd1378** [cpreston321/nuxt-swiper#59]
Hi
it seems like tree shaking is not working
I'm only using `Swiper`, `SwiperAutoplay` and `SwiperSlide`, and the generated chunk file for it is ~ 147.js

is this size normal ? is this a bug or expected behavior ?

**Comment by dloop-mb** [comment]
I think tree shaking is working. Even without using the `modules` configuration nuxt-swiper only loads the modules that are actually used in the template.

template:
```
  <Swiper
    :modules="[SwiperAutoplay, SwiperPagination]"
```

analyze:
swiper-vue 178.81kb
![image](https://github.com/cpreston321/nuxt-swiper/assets/57012534/75a9f6e8-4576-4f29-80a3-2554b02e82d3)

template:
```
  <Swiper
    :modules="[SwiperAutoplay, SwiperPagination, SwiperHistory]"
```

analyze:
swiper-vue 180.75kb
![image](https://github.com/cpreston321/nuxt-swiper/assets/57012534/616e1d27-35ce-4c20-b75e-e4f1e44cd92d)

**But**, the `@vue` part is 88.36kb big. Isn't this something that could be reused from nuxt3 core dependencies? (Sorry, no nuxt3 expert myself)

**Comment by jd1378** [comment]
I think vue part name is just coincidentally same as vue, it probably just means that part of swiper is made specifically for vue

overall I don't know how much of swiper is actually essential, It's very big, and even with tree shaking it's still big
I'm closing this as I don't think this is an issue of nuxt-swiper any more
