### ISSUE TITLE
Thumbs gallery not connecting to main swiper slider

### ISSUE THREAD

**Issue by lmoroz** [cpreston321/nuxt-swiper#62]
I am currently using a basic [Nuxt Swiper](https://nuxt.com/modules/swiper) example and would like to add a thumbs gallery to the slider. Although the main slider and thumbs gallery are both functioning correctly, they are not currently connected. Can you give me some guidance on how to connect the two components?

The code is here: https://stackblitz.com/edit/github-etseqm?file=app.vue

**Comment by cpreston321** [comment]
The elements have to live within the `Swiper/>` element for it to work correctly. Here is a working example based on your example above: 

https://stackblitz.com/edit/github-etseqm-mhtkok?file=app.vue

**Comment by lmoroz** [comment]
> The elements have to live within the `Swiper/>` element for it to work correctly. Here is a working example based on your example above:
> 
> https://stackblitz.com/edit/github-etseqm-mhtkok?file=app.vue

I updated my code, it was not saved for some reason. Your example not based on my code

**Comment by lmoroz** [comment]
resolved
