### ISSUE TITLE
Swiper 9.4.0 issue with (typeerror undefined onTouchMove) 

### ISSUE THREAD

**Issue by thamudi** [cpreston321/nuxt-swiper#66]
There is an issue with swiper js v 9.4.0  when swiping the slider.

`TypeError: undefined is not an object(evaluating swiper.freeMode.onTouchMove`

Upgrading it to ver 9.4.1 fixes this issue.

[Swiper v9.4.1 release](https://github.com/nolimits4web/swiper/releases/tag/v9.4.1)
[Github related issue](https://github.com/nolimits4web/Swiper/issues/6751)

**Comment by cpreston321** [comment]
I will create a patch fix soon to upgrade deps. 

In the meantime I am going to start the move to web components! #55 

Thanks,
CP 🚀
