### ISSUE TITLE
How to lazy load nuxt-swiper

### ISSUE THREAD

**Issue by js1k** [cpreston321/nuxt-swiper#69]
I installed nuxt-swiper as document. but nuxt-swiper.js is too large when vsite page. 
I want to lazy load nuxt-swiper.js， how to config ?

**Comment by cpreston321** [comment]
It seems that you are trying to do this ? https://swiperjs.com/swiper-api#lazy-loading

I would try adding the `loading="lazy"` to img props.

**Comment by js1k** [comment]
您好：
您的邮件我已经收到，谢谢你的关心与支持。我会尽快给您满意的答复。祝你身体健康，万事如意
收件人BWW
