### ISSUE TITLE
How to listen to events

### ISSUE THREAD

**Issue by sanu-krishnan** [cpreston321/nuxt-swiper#70]
Is there a way to listen to events ?

Goal is to identify the index of current slide and run some animations on each slide while enter and exit.

**Comment by cpreston321** [comment]
Have you tried any of the https://swiperjs.com/swiper-api#events ? It seems like you are looking for `@activeIndexChange="onIndexChange"`

**Comment by sanu-krishnan** [comment]
Yea, tried before. But was using the wrong syntax.
Working perfectly with the syntax you shared 🔥
Thank you
