### ISSUE TITLE
Destroy Nuxt-Swiper on large screens

### ISSUE THREAD

**Issue by boateng-ampaw** [cpreston321/nuxt-swiper#72]
How do I kill/destroy Nuxt Swiper on large screens? I have a gallery that I would want to as a single-item-per-view slider only on mobile screens. Thank you

**Comment by cpreston321** [comment]
@boateng-ampaw 

1. I would listen for screen size changes or a nuxt module like `@vueuse/nuxt` to leverage the breakpoint compostable. 
2. Then I would get the swiper instance using `@swiper="onSwiper"` to set as variable.
3. Then use `swiper.destroy()` & `swiper.init()` for destroying and re-initializing swiper.
