### ISSUE TITLE
Missing "./modules" specifier in "swiper" package

### ISSUE THREAD

**Issue by notflip** [cpreston321/nuxt-swiper#74]
I updated the package to 1.2.0, coming from a 0.xx version, now I'm getting the error
`Missing "./modules" specifier in "swiper" package`

My config is
```
    modules: [
        '@nuxtjs/i18n', 'nuxt-swiper'
    ],
    swiper: {
        modules: ['pagination']
    }
```

**Comment by cpreston321** [comment]
@notflip I can't seem to re-produce this on my ENV. Can you make a re-production please 🙏🏼

**Comment by cpreston321** [comment]
The only thing I can think of, is that swiper is not on the latest version that contains `/modules` in the `package.json`

**Comment by cpreston321** [comment]
I would try deleting `node_modules/` and `.lock` file and do a re-install

**Comment by ShiriCZ** [comment]
Happend to me also after I upgraded to Nuxt 3.6.5 via `npm upgrade --force`. Removing .lock and node_modules did not resolve the problem..

**Comment by cpreston321** [comment]
@ShiriCZ Is it possible that you take a screenshot of the exports within the `package.json` within `node_modules/swiper/package.json` ? I can only see this if it is on the incorrect version of `swiper`.

**Comment by notflip** [comment]
Updating to the latest version of Swiper fixed the issue, I was on 8.x.x, I'm not on 10.0.4. Thank you everyone

**Comment by cpreston321** [comment]
@notflip `nuxt-swiper` should be including this on install. In most cases if you control the swiper version in further releases there might be a high chance of the package breaking. 

Glad it helped!

**Comment by reslear** [comment]
yes, this problem installing:

```
pnpm why swiper
```

```
dependencies:
nuxt-swiper 1.2.2
└── swiper 10.3.0
```

get version https://github.com/cpreston321/nuxt-swiper/blob/main/package.json#L47 and install fixed

`pnpm add swiper@10.2.0`

done
