### ISSUE TITLE
Cannot import SwiperOptions from 'swiper/types'

### ISSUE THREAD

**Issue by RomanSkrypnik** [cpreston321/nuxt-swiper#79]
I want to use SwiperOptions for props, but facing this issue:

![image](https://github.com/cpreston321/nuxt-swiper/assets/44501848/1b446719-2108-417e-80f5-3bbf4df31037)
![image](https://github.com/cpreston321/nuxt-swiper/assets/44501848/0de8042b-135a-4424-a331-d0a0800d69ff)

**Comment by cpreston321** [comment]
Can you check to see if what the exports are in the `package.json` within `node_modules/swiper/package.json` ?

**Comment by RomanSkrypnik** [comment]
Version is 10
I have decided just to downgrade my `nuxt` to 0.1.9 which has `swiper` version 8.4.5 - it works fine
Also downgrade fixed `free-mode`
