### ISSUE TITLE
There is no `SwiperModuleOptions` type exported

### ISSUE THREAD

**Issue by lukasaric** [cpreston321/nuxt-swiper#82]
@cpreston321  Is there a possibility to export the `SwiperModuleOptions` interface so that the `SwiperModulesType` is accessible?

**Comment by cpreston321** [comment]
May I ask what you are using it for? Like a use case.

**Comment by lukasaric** [comment]
> May I ask what you are using it for? Like a use case.

Yes, sure. In the current project we use Nuxt 3 and we decides to separate nuxt config options in a smaller chunks. 
That being said, nuxt-swiper is also separated and TS cannot recognize properly modules prop type. So we just need to use ‘as’ assertion with the type that I cannot access.
