### ISSUE TITLE
nuxt-swiper loads on every page

### ISSUE THREAD

**Issue by zarskilukasz** [cpreston321/nuxt-swiper#84]
Hi, I noticed something - nuxt-swiper loads its files on every page even though I only need it where it is used. This affects overall performance on mobile devices.

**Comment by PatrikBird** [comment]
Did you consider that this might happen due to prefetching? Nuxt prefetches every NuxtLink within the viewport.

**Comment by zarskilukasz** [comment]
Sure. In that case, why does prefetching only download the swiper and not other components? And why is it so high on the list of downloaded files?

**Comment by zarskilukasz** [comment]
![Zrzut ekranu 2023-10-4 o 14 07 30](https://github.com/cpreston321/nuxt-swiper/assets/14441265/d76159c4-607e-4450-b011-9860dc2b938b)

Swiper is not used on this site

**Comment by Pezhvak** [comment]
I'm having the same issue

**Comment by LukasHechenbergerID** [comment]
@Pezhvak @zarskilukasz @PatrikBird i have switched to the web components: https://swiperjs.com/element

It's relatively easy and my speed scores went up a notch. (Even though i didn't even try to optimize it):

- npm install swiper
- create a plugin in nuxt (eg. /plugins/registerSwiper.ts)
- ```
import { register } from 'swiper/element/bundle';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.hook('app:created', () => {
        register();
    });
});
```
- Add this to the nuxt config so intellisense doesn't annoy you:
```
vue: {
        compilerOptions: {
            isCustomElement: (tag) => tag.startsWith('swiper-'),
        },
    },

```
It doesn't change much from the syntax, here is an example component:
```
<template>
    <swiper-container
        :pagination="{
            enabled: true,
            clickable: true,
        }"
        :watch-slides-progress="true"
        :breakpoints="breakpoints"
        :slides-per-view="1.1"
        space-between="16"
        :speed="500"
        navigation="true"
        :autoplay="{
            enabled: autoplayEnabled,
            disableOnInteraction: true,
            pauseOnMouseEnter: true,
        }">
        <swiper-slide> 1 </swiper-slide>
        <swiper-slide> 2 </swiper-slide>
    </swiper-container>
</template>

<script setup lang="ts">
    export interface Props {
        autoplayEnabled?: boolean;
    }

    const props = withDefaults(defineProps<Props>(), {
        autoplayEnabled: false,
    });

    // Breakpoints for different screen sizes
    const breakpoints = ref({
        640: {
            slidesPerView: 1,
            spaceBetween: 16,
        },
        768: {
            slidesPerView: 2,
            spaceBetween: 24,
        },
        1024: {
            slidesPerView: 2,
            spaceBetween: 24,
        },
        1280: {
            slidesPerView: 3,
            spaceBetween: 24,
        },
        1536: {
            slidesPerView: 3,
            spaceBetween: 24,
        },
    });
</script>

```

**Comment by liaow-ww** [comment]
hi, I solved it. I had the same problem before. You don’t need to configure this module in modules in nuxt.config.ts.
You can introduce it like this, https://swiperjs.com/element
![image](https://github.com/cpreston321/nuxt-swiper/assets/115768717/f57c7fee-1ea6-43b9-bf34-a7dfd64f4b14)
But you need to check the documentation of vue-swiper, not the documentation of nuxt-swiper.
This can reduce the resource loading of other pages that do not use swiper
hope it can help you~

**Comment by liaow-ww** [comment]
> @PatrikBird I have the same issue i think. Even if it is due to prefetching it shouldn't be the first thing to fetch after the html page (the hydration js files of the components of the page get loaded at the same time).我想我有同样的问题。即使它是由于预取，它也不应该是html页面之后首先要获取的东西（页面组件的hydration js文件同时加载）。
> 
> I don't know if this Stackblitz illustrates it good but here you go: https://stackblitz.com/edit/github-qsv57x?file=app.vue我不知道这个 Stackblitz 是否很好地说明了它，但你去吧：https://stackblitz.com/edit/github-qsv57x?file=app.vue Here all the js and css of the swiper modules get loaded almost at the beginning even if dont use them in a file.在这里，swiper 模块的所有 js 和 css 几乎在一开始就被加载，即使没有在文件中使用它们。
> 
> ![image](https://private-user-images.githubusercontent.com/93664840/269879783-89612984-5619-4c77-8211-11f198c8766f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjAzOTcsIm5iZiI6MTcwMTI2MDA5NywicGF0aCI6Ii85MzY2NDg0MC8yNjk4Nzk3ODMtODk2MTI5ODQtNTYxOS00Yzc3LTgyMTEtMTFmMTk4Yzg3NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMjFlNjIxOGI2YzI5NWQyOTM0ZDMzZmUyNTcyNDNlNWE5YjhkMTM5MzY3N2ZmNWViMTQxZTkyMDQyZDU1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBN7_n-iNZahkadDApQma7_y9KwCH8lTqw55ke8-gs4)

This can be prevented by adding a configuration to prevent redundant swiper style loading.
add it in nuxt.config.ts like this:
swiper: {
    modules: ['navigation', 'thumbs', 'free-mode']
  }

but there can be a better way, see my answer
