### ISSUE TITLE
Nuxt multiple swiper on single page

### ISSUE THREAD

**Issue by matrixmandeep** [cpreston321/nuxt-swiper#90]
@cpreston321  I'm getting the issue on nuxt swiper that when navigate the one swiper then other one is automatically swiping.

**Comment by cpreston321** [comment]
Please submit Reproduction 🙏🏼 -> https://stackblitz.com/github/cpreston321/nuxt-swiper/tree/main/examples/swiper-basic?file=app.vue

**Comment by matrixmandeep** [comment]
https://stackblitz.com/edit/github-nxl83s?file=app.vue,.nuxt%2Fcomponents.d.ts,components%2Fswiper-two.vue
here is the reference if you use the 2nd carousel navigation above one will swiped along with the second one.

**Comment by cpreston321** [comment]
@matrixmandeep This has to do with defining the navigation class to the same bindings. Example -> `.siwper-button-next`. To get around this it's best to use `useSwiper()` to target the instance you want, then customize the buttons for styling. 

Within swiper itself it creates an event listener for each of those define for each Swiper instance. To get around this you can either create next bindings like so: 

---

## Swiper One 

```
:navigation="{
    nextEl: '.swiper-button-next-one',
    prevEl: '.swiper-button-prev-one',
}"
````

---

## Swiper Two

```
:navigation="{
    nextEl: '.swiper-button-next-two',
    prevEl: '.swiper-button-prev-two',
}"
````

or use the composable `useSwiper()` to create the navigation: 


Example link: https://stackblitz.com/edit/github-nxl83s-kpxiyu?file=components%2Fswiper-two.vue
