### ISSUE TITLE
Module SwiperMousewheel not working

### ISSUE THREAD

**Issue by sebastiantiede** [cpreston321/nuxt-swiper#99]
Environment:
nuxt: 3.6.1
nuxt-swiper: 1.2.2

slider.vue
```vue
<Swiper ref="$swiper" :class="sliderClass" :slides-per-view="'auto'" @update="onUpdate" :mousewheel="true" :modules="[SwiperMousewheel]">
    <slot></slot>
    <TilesSliderControls type="tiles" />
</Swiper>
```

The slideshow is not changing. I'm not receiving any feedback or error message. 
Thank you for your quick assistance.

**Comment by vinatechpro** [comment]
> Environment: nuxt: 3.6.1 nuxt-swiper: 1.2.2
> 
> slider.vue
> 
> ```
> <Swiper ref="$swiper" :class="sliderClass" :slides-per-view="'auto'" @update="onUpdate" :mousewheel="true" :modules="[SwiperMousewheel]">
>     <slot></slot>
>     <TilesSliderControls type="tiles" />
> </Swiper>
> ```
> 
> The slideshow is not changing. I'm not receiving any feedback or error message. Thank you for your quick assistance.

Add option :direction="horizontal" or :direction="vertical" 
https://swiperjs.com/swiper-api#param-direction

**Comment by Milk-Ice** [comment]
thank you! I meet the same problem,finally sovle by adding `:modules="[SwiperMousewheel]"`,but i dont know why ,please tell me ,thank you

**Comment by cpreston321** [comment]
@Milk-Ice In the vue implementation you have to specify which module you want to enable. Within the README I have a list of auto-imports that you can use but this current implementation will be deprecated in favor of Swiper Elements reference in the pinned issue. 

Thanks,
CP
